version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache-progweb
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./:/var/www/html/
        ports:
            - 8000:80
    # db:
    #     container_name: db
    #     image: mariadb
    #     restart: always
    #     environment:
    #         MYSQL_DATABASE: 
    #         MYSQL_ROOT_PASSWORD: 
    #         MYSQL_USER: 
    #         MYSQL_PASSWORD: 
    #     volumes:
    #         - ./volume-data/:/var/lib/mysql/
    # adminer:
    #     container_name: adminer
    #     image: adminer
    #     restart: always
    #     ports:
    #         - 8080:8080
