version: '3.8'
services:
  web:
    # volumes:
    #   - ./src:/home/app
    #   - ./src/node_modules:/home/app/node_modules

    build:
      context: ./
      dockerfile: Dockerfile

    ports:
      - "3000:3000"
 