[default]
address = "0.0.0.0"
port = 4000
workers = 5
keep_alive = 5
ident = "Rocket"
log_level = "normal"
temp_dir = "/tmp"

[default.shutdown]
ctrlc = true
signals = ["term", "hup"]
grace = 5
mercy = 5
