version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache-intro
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./site/:/var/www/html/
        ports:
            - 8001:80

